version: "3.9"
services:
    users-app-db:
        container_name: tk-app-db
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "VerySecurePassword321"
            ACCEPT_EULA: "Y"
        ports:
            - "8000:1433"
